---
# tasks file for roles/apache
- name: Install Apache (apache2)
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Start and enable apache2
  service:
    name: apache2
    state: started
    enabled: yes

- name: Create HTML page with hostname and IP
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
